### ISSUE TITLE
Reconfigure device IP and polling interval

### ISSUE THREAD

**Issue by rpalacios-ak** [stanus74/home-assistant-saj-h2-modbus#10]
Hi.

First of all, I'd like to congratulate you for you work. I've been polling SAJ H2 (S1) Modbus via Node-Red and sending the data to Home Assistant through MQTT, but Ii consider very useful for new users being able to do it directly form HA, so I'm giving a try to your integration and willing to help in what I can.

My question: Is it possible to reconfigure the device IP address and polling interval once the integration has been configured for the first time after install?. I cannot see the "Configure" option other integrations have.

Thank you. Kind regards.

**Comment by stanus74** [comment]
The configuration changes have been addressed in [Pull Request #11](https://github.com/stanus74/home-assistant-saj-h2-modbus/pull/11)

This PR implements the requested configuration options for the integration, making it possible to update configurations after setup. Feel free to review the PR and provide feedback.

Once the PR is merged, this issue can be closed.
