### ISSUE TITLE
Feature "Loading from Grid"

### ISSUE THREAD

**Issue by UDicke** [stanus74/home-assistant-saj-h2-modbus#12]
`Even controlling the battery charging times is possible in HA with the integrated Modbus module. We will soon provide a guide on GitHub with code for this.`

can be read at the end of https://github.com/stanus74/home-assistant-saj-h2-modbus#additional-imformation

Is there any idea when this will be available? Is there a description of the planed funtionality for this?

Thank you for this integration including the ongoing support!

**Comment by stanus74** [comment]
is currently being developed and is in the test phase
