### ISSUE TITLE
Read external sensors

### ISSUE THREAD

**Issue by tims04** [stanus74/home-assistant-saj-h2-modbus#15]
Hi,

I have a SAJ H2-5K-S2 plus battery, and an additional stand-alone solar inverter.   Output from the stand-alone solar inverter is measured by external metering device which is connected to the SAJ H2-5K-S2 (RS-485 I think?).

The SAJ (elekeeper) app measures the SAJ H2's PV1+PV2 (Watts) PLUS the PV generated by the stand-alone inverter through the measuring device connected to the SAJ Inverter.  

Is there a modbus register where the external metering devices can be read?

Let me know if you need full register output from my inverter.

**Comment by stanus74** [comment]
In the Modbus protocol, PV3 + PV4 are described by register address Hex 4077 - 407C.
As the H2 inverter only has 2 string inputs, the values of an inverter connected in parallel could perhaps be displayed here.
Try to read the registers e.g. with QmodMaster Tool
