### ISSUE TITLE
saj_pv2_power incorrect value

### ISSUE THREAD

**Issue by mrf68** [stanus74/home-assistant-saj-h2-modbus#16]
I love this intergration, thanks for the update.

issue: saj_pv2_power vakue shows 0,98 where it should be 98. saj_pv_power shows the correct value (I only have pv2 connected)

Kind regards,
Martin

**Comment by stanus74** [comment]
This commit fixes the problem 20f020f0521fe9c902ca8908f5b0d0462bc441fc
