### ISSUE TITLE
pv1 & pv2 multipilers set wrong

### ISSUE THREAD

**Issue by pborsiak** [stanus74/home-assistant-saj-h2-modbus#17]
Hi,

I have strange strings readings once upgrated to 1.6.1. my total pv output is read ok, but pv1 and pv2 are 1/100 of before reads. Please refer to screenshot 
![Screenshot_2024-11-23-17-54-09-696_io homeassistant companion android](https://github.com/user-attachments/assets/3fb14437-7f29-44ec-b383-f4fe64a8c1a7

Please close as looks like it is addresed now

**Comment by stanus74** [comment]
bug is fixed in version v1.6.2
