### ISSUE TITLE
SAJ inverter temperature not available

### ISSUE THREAD

**Issue by mrf68** [stanus74/home-assistant-saj-h2-modbus#7]
Hello,

I'm a fan of this intergration. Since sept 16th, 23:14h, the inverter temperature is unkown. All other information is still available. Maybe SAJ changed something in their settings?

Kind regards,
Martin
![Schermafbeelding 2024-09-21 101928](https://github.com/user-attachments/assets/f5d4f74a-4ab5-4d75-9dfb-17a9dce1b0af)

**Comment by jsjhb** [comment]
release 1.5.2 removed "test_values" in read_modbus_realtime_data but are still reference in assignment. This leads to an error on data gathering, and to undefined values.
Pull request #8 should fix this.

**Comment by stanus74** [comment]
Bugfix in retrieve real-time data fixed with Version 1.5.3
