### ISSUE TITLE
Works with SAJ H1

### ISSUE THREAD

**Issue by Mr-Alicates** [stanus74/home-assistant-saj-h2-modbus#9]
Hello!

I tried this repository on my SAJ H1-S2 with a wifi dongle (I don't know the exact model, I know is from Saj and is not the AIO3 model).

It seems to be working, but I'll need some time to monitor the data points and ensure everything is consistent.

👍

**Comment by stanus74** [comment]
The registers of the H1 do not match 100% with those of the H2.

Please compare the two Modbus protocols of 2020 with the one in the ZIP file for the H2/HS2 inverter.

This is the 2020 protocol for H1 
https://github.com/paolosabatino/saj-mqtt-ha/blob/master/doc/modbus_protocol_saj_2020.pdf

here is the one for H2 (with Excel table) 
saj-h2-modbus.zip >
https://github.com/stanus74/home-assistant-saj-h2-modbus
